### ISSUE TITLE
How to get PRs merged

### ISSUE THREAD

**Issue by benblack86** [mwunsch/handlebars.scala#72]
Seems like this project is dead? We would love to get this PR merged (or commented on) https://github.com/mwunsch/handlebars.scala/pull/57, because then we don't need to maintain an internal forked version. What can we do to speed up the process? Do you need more maintainers?

**Comment by nightscape** [comment]
The network graph now looks like this, which is a clear indicator that there is continued interest in the project, but the original maintainer(s) don't have time to take care of it anymore:
![image](https://user-images.githubusercontent.com/35170/103772048-22a43480-5029-11eb-905e-ef76f3305e84.png)
If noone objects, I would go ahead and fork this repo to a neutral repository and add the people that have worked on forks as maintainers.

**Comment by mwunsch** [comment]
Hi @nightscape and others. If you'd like to take over mainternship of this repo, I'd be open to discussion. You are correct, I no longer have the time nor the interest in this project, and would happily turn it over to someone who finds it useful.

**Comment by nightscape** [comment]
Hi @mwunsch, thanks for responding so quickly!
I see two ways forward:

1. We leave the Git repo under your handle and you add a few people as admins on it. The harder part is setting up publishing so that you don't have to do anything manual. For this we would need a bit of your time w.r.t. Sonatype login & PGP key setup.
2. We move the Git repo to a new organization and change the Maven organization (and probably for consistency purposes the package names as well) correspondingly. In that case it would be just like setting up a new Sonatype account for which we probably wouldn't need your time and help.

Do you have any preferences?

**Comment by nightscape** [comment]
@mwunsch did you find time to consider the options?
If you don't care, just add me as an admin to the project and I will take it from there :wink: 
I would probably go for option 2 then.

**Comment by mwunsch** [comment]
@nightscape My preference is for Option 2!

**Comment by nightscape** [comment]
@mwunsch ok! If you can add me as admin to the repo I'll take it from there :+1:
